---

- name: Enable IP forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'

- name: Proxy configure 
  lineinfile:
    path: /etc/environment
    line: 'http_proxy=172.22.86.10:8888'

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: add Nginx repo
  copy: 
    src: roles/common/files/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    force: no

- name: Install required software  
  yum: 
    name :
      - qemu-kvm
      - libvirt
      - libvirt-python
      - libguestfs-tools
      - virt-install
      - wget
      - nginx
    state: present

- name: Start libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create necessary folders
  file:
    path: "{{ item }}"
    state: directory
    owner: qemu
    group: qemu
  with_items:
    - /opt/virt
    - /opt/virt/images
    - /opt/virt/meta-data

- name: Get cloud image
  get_url:
    url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
    dest: /opt/virt/images
    owner: qemu
    group: qemu
      
- name: Decompress image
  command: xz --decompress CentOS-7-x86_64-GenericCloud.qcow2.xz
  args:
    chdir: /opt/virt/images