---

- name: Create config script
  template: 
    src: templates/vm_conf.j2
    dest: /opt/virt/meta-data/vm_{{ vm1_ip }}_{{ vm2_ip }}.sh
    mode: '0654'
    owner: qemu
    group: qemu
    force: yes

- name: Create VM
  script: /opt/virt/meta-data/vm_{{ vm1_ip }}_{{ vm2_ip }}.sh "{{ vm1_ip }}" "{{ vm2_ip }}"

- name: Remove script
  command: rm -f /opt/virt/meta-data/vm_{{ vm1_ip }}_{{ vm2_ip }}.sh
      